#!/bin/bash -e
source "$APPDIR/freedv-gui/rade-venv/bin/activate"
logger "In AppRun"
PYTHONPATH="$APPDIR/freedv-gui/build_linux/rade_src:$PYTHONPATH" "$APPDIR/freedv-gui/build_linux/src/freedv $1 $2
deactivate
