#!/bin/bash -e
# Change to the directory where this script is located
cd "$(dirname "$(realpath "$0")")"
PYTHONPATH=$APPDIR/usr/bin/rade_src:
export PYTHONPATH
. $APPDIR/usr/bin/rade-venv/bin/activate
$APPDIR/usr/bin/freedv --verbose
