#!/bin/bash -e
cd "$APPDIR/freedv-gui"
PYTHONPATH="$APPDIR/freedv-gui:$PYTHONPATH"
export PYTHONPATH
logger FreeDV "In AppRun"
. $APPDIR/freedv_gui/rade-venv/bin/activate
$APPDIR/freedv-gui/build_linux/src/freedv --verbose
